services:
  - type: web
    name: peachy
    runtime: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
